### ISSUE TITLE
UiO core RI Data publishing workshop

### ISSUE THREAD

**Issue by rukayaj** [uio-mana/CORE-Events#29]
# Quick Facts
## Abstract
The Natural History Museum MaNa group and Norwegian Global Biodiversity Information
Facility (GBIF) node invite students, PhDs, postdocs, researchers and faculty at the University
of Oslo to a 1-day workshop on 17 September 2024. More details to follow in the autumn!
This event is designed to assist you in publishing your data as Darwin Core Archives, with expert
guidance on the Darwin Core standards.

## Logistics
- **External Link:** https://github.com/uio-mana/Events/files/14945657/Workshop.save-the-date.Invitation_.Publish.Your.Data.as.Darwin.Core.Archives.pdf
- **Dates**: 2024-09-17; 09:00-16:00 CET
- **Venue**: TBD
- **Host(s):** [MANA](https://www.nhm.uio.no/english/research/groups/mana/index.html)

## Related Project(s)
[CoreRI](https://github.com/uio-mana/CORE-Projects/issues/7)

# Post-Event Summary
## Outcome
Event has not happened yet.

**Comment by rukayaj** [comment]
Programme for online SA workshop is [here](https://docs.google.com/document/d/18514YH_-4t1PXB1FElJTlHqfaW7ICh9PtTETj4CXcKw/edit?usp=sharing)

**Comment by rukayaj** [comment]
Data publishing workshop advert draft:

# Workshop Invitation: Publish Your Data as Darwin Core Archives

The Norwegian Global Biodiversity Information Facility (GBIF) node invites biosciences students, PhDs, and postdocs at the University of Oslo to a 1-day workshop. This event is designed to assist you in publishing your data as Darwin Core Archives, with expert guidance on the Darwin Core standards.

## By the end of the workshop, you will:

- Have published your data or be able to do so independently with a few simple steps.
- Understand the Darwin Core standards and the importance of publishing data in Darwin Core Archives.
- Be capable of independently publishing your future data in Darwin Core Archives.

## Why Publish Your Data on GBIF.org?

Publishing your data contributes to the global scientific community by making your research accessible for further studies, policy-making, and educational purposes. It enhances the visibility of your work and integrates it into a global database that supports open and reproducible science.

## The Importance of Publishing Your Data

Publishing your datasets is crucial for open and reproducible science, fostering a transparent process where your research can be validated, challenged, and built upon. This approach accelerates discovery and innovation in the biosciences.

## Workshop Details

**Who Should Attend:** Biosciences students, PhDs, and postdocs at the University of Oslo. No prior experience is required.

**What to Bring:** Your data and a laptop. Dummy data will also be available for practice.

**Prerequisites:** None.

## Provisional Schedule

- **Morning:** Introductory Presentations
  - Introduction to biodiversity data publishing (60 minutes)
  - Introduction to GBIF (15 minutes)
  - Introduction to Darwin Core (15 minutes)

- **Rest of the Day:** Hands-on Data Publishing
  - Expert assistance available.
  - Learn through hands-on experience and collaborative problem-solving.
  - Convert data to Darwin Core Archive.
  - Map parameter names to Darwin Core terms.
  - Data restructuring where necessary.
  - Use GBIF’s Integrated Publishing Toolkit (IPT): [https://www.gbif.org/ipt](https://www.gbif.org/ipt)

## Prize for Best Dataset Published

To encourage excellence in data publication, a prize will be awarded to the best dataset published by the end of the workshop.

## Are My Data Suitable?

Suitable data for Darwin Core Archives include species lists and associated measurements or facts. If you have questions about your data's suitability or any other inquiries, please contact helpdesk@gbif.no.

**Comment by cjandrew** [comment]
By the way, see also material in the [Google Drive folder](https://drive.google.com/drive/folders/1KCVavh7KXvONvcQ95k6Fh-mXGiE9kGSx?usp=share_link)

**Comment by cjandrew** [comment]
[Workshop "save-the-date" Invitation: GBIF Data Use and Application](https://docs.google.com/document/d/1ARMOMRdfcpoKTI6FwN0uixO0YXGn6I_pMLerclp7Y9w/edit?usp=sharing)

**Comment by cjandrew** [comment]
FYI, I do not know how to post this to the MaNa events page

**Comment by dagendresen** [comment]
[The Core RI data publication workshop is coming up SOON!](https://www.nhm.uio.no/english/research/groups/mana/events-mana/data-publication-workshop.html)
The home page states the agenda below. 
Who will teach each presentation?
Who of us will be there?
When do we start (hour of the day)?
When do we close (hour of the day)?
Do we order any food? 
Did anybody order any food? (the registration form is asking for food preferences)

> Morning: Introductory Presentations
> Introduction to biodiversity data publishing (60 minutes)
> Introduction to GBIF (15 minutes)
> Introduction to Darwin Core (15 minutes)
> Rest of the Day: Hands-on Data Publishing
> Expert assistance is available.
> Learn through hands-on experience and collaborative problem-solving.
> Convert data to Darwin Core Archive.
> Map parameter names to Darwin Core terms.
> Data restructuring where necessary.
> Use GBIF’s Integrated Publishing Toolkit (IPT): https://www.gbif.org/ipt

**Comment by rukayaj** [comment]
I just checked the nettskjema, we have no registrations for the data publication workshop :( I will contact the people @cjandrew emailed earlier and ask them to circulate the ads again.

**Comment by rukayaj** [comment]
Rooms booked: 
17 Sep. :  [DSC-Oasen, Georg Sverdrups hus, Floor 01](https://link.mazemap.com/XqJ3htvq)
22 Oct. : [IT-auditorium 3, Vilhelm Bjerknes' hus](https://use.mazemap.com/#v=1&config=uio&campusid=797&zlevel=1&center=10.723437,59.940168&zoom=18&sharepoitype=poi&sharepoi=1000956713)

**Comment by dagendresen** [comment]
Workshop completed
