### ISSUE TITLE
UiO core RI Drop in virtual helpdesk

### ISSUE THREAD

**Issue by rukayaj** [uio-mana/CORE-Events#31]
# Quick Facts
## Abstract
We are going to be holding an open drop-in hybrid data & programming helpdesk every two months during 2024.
We can help with:
- publishing your biodiversity related data to GBIF, the Global Biodiversity Information Facility (https://gbif.org/)
- biodiversity data analysis
- biodiversity data management
- creating a data paper for publication (a peer reviewed document describing a dataset, published in a journal - it takes effort to prepare, curate and describe data, and this deserves recognition)
- making your R, Python (or any other) code reproducible in accordance with Open Science
- code design best practice
- transparent workflows and working with github
- making your data FAIR
- possibly with data storage solutions for your biodiversity data

Dates:
- 14 February 2024 @ 14:00 - 15:00
- 17 April 2024 @ 14:00 - 15:00
- 12 June 2024 @ 14:00 - 15:00
- 14 August 2024 @ 14:00 - 15:00
- 16 October 2024 @ 14:00 - 15:00
- 11 December 2024 @ 14:00 - 15:00

## Logistics
- **External Link:** https://www.nhm.uio.no/english/research/projects/biodt/events/HybridHelpdesk.html
- **Dates**: 2024-02-14; 14:00-15:00 CET
- **Venue**: Office K07, Lids Hus, Tøyen Campus & https://uio.zoom.us/my/gbif.no
- **Host(s):** [MANA](https://www.nhm.uio.no/english/research/groups/mana/index.html)

## Related Project(s)
[CoreRI](https://github.com/uio-mana/CORE-Projects/issues/7)

# Post-Event Summary
## Outcome
Event has happened. No attendance.

**Comment by rukayaj** [comment]
How did we say we were going to advertise this?

**Comment by ErikKusch** [comment]
Should we put together a website [like this](https://www.med.uio.no/forskning/kjernefasiliteter/bioinformatikk/)? I would also advertise via the coders and biostatisticians mailing list here at NHM... but how do we reach Blindern?

**Comment by rukayaj** [comment]
Maybe Live can help us advertise to people on Blindern? We could put together a website if you want? We could also just do a general github issue and link to that in an email maybe? It's a bit easier to maintain than a webpage.

Email draft:

Dear UiO students and employees,

We are going to be holding an open drop-in virtual data & programming helpdesk every two months during 2024. 

We can help with:
- publishing your biodiversity related data to GBIF, the Global Biodiversity Information Facility (https://gbif.org)
- biodiversity data analysis
- biodiversity data management
- creating a data paper for publication (a peer reviewed document describing a dataset, published in a journal - it takes effort to prepare, curate and describe data, and this deserves recognition)
- making your R, Python (or any other) code reproducible in accordance with Open Science
- code design best practice 
- transparent workflows and working with github
- making your data FAIR
- possibly with data storage solutions for your biodiversity data

Dates:
16 February 2024 @ 14:00
16 April 2024 @ 14:00
17 June 2024 @ 14:00
16 August 2024 @ 14:00
16 October 2024 @ 14:00
16 December 2024 @ 14:00

Zoom link: https://uio.zoom.us/my/gbif.no . Please add to your calendars!

Best wishes, 
The Machine-readable Nature (MaNa) Research Group at NHM

**Comment by ErikKusch** [comment]
Agreed that the github issue would be much easier to maintain, but am afraid the we would not get a lot of views on it from folks who actually need the help - what do you think?

Getting Live to help with advertising is a great idea.

Regarding dates, could it be better to fix the dates to something like "the first Wednesday in each second month" instead of bouncing dates around the weeks? I am torn on it. The current solution gives more freedom to join for folks who have strict schedules for certain weekdays, my proposal would give us more planning stability. Thoughts?

**Comment by rukayaj** [comment]
14 February 2024
17 April 2024
12 June 2024
14 August 2024
16 October 2024
11 December 2024

3rd wednesdays

**Comment by rukayaj** [comment]
We made a webpage and linked from https://www.nhm.uio.no/english/research/groups/mana/index.html

**Comment by ErikKusch** [comment]
We have linked from [this page](https://www.nhm.uio.no/english/research/groups/mana/index.html) to the newly created [helpdesk advertising page](https://www.nhm.uio.no/english/research/projects/biodt/events/HybridHelpdesk.html). Feedback and changes are welcome. I believe it should be moved from BioDT to the [infrastructure pages](https://www.nhm.uio.no/english/research/infrastructure/), but we (Rukaya and I) do not have write permission there. @dagendresen , do you by any chance?

**Comment by rukayaj** [comment]
I suggest we actually just leave it at https://www.nhm.uio.no/english/research/projects/biodt/events/HybridHelpdesk.html seeing as we need to circulate it (first one is happening in less than 2 weeks now). I'm going to ask Live to help circulate it.

**Comment by mariapie** [comment]
Hei, here is Elisa. I think we surely can start circulating it at DSC UiO, we have a newsletter there. Also, i was thinking i could make it circulate through TheCarpentry community at UiO. Maybe something that could be send through social media channel as well? I was thinking also we will start running the Research data courses, and there we could have an advertise for this as well

**Comment by rukayaj** [comment]
Hi! That all sounds great, thanks! I'm not sure how to send it through the social media channel, do you know how to do that?

**Comment by mariapie** [comment]
I was thinking to reach out to the communication group at UiO, they should be the one having access.

**Comment by dagendresen** [comment]
> We have linked from [this page](https://www.nhm.uio.no/english/research/groups/mana/index.html) to the newly created [helpdesk advertising page](https://www.nhm.uio.no/english/research/projects/biodt/events/HybridHelpdesk.html). Feedback and changes are welcome. I believe it should be moved from BioDT to the [infrastructure pages](https://www.nhm.uio.no/english/research/infrastructure/), but we (Rukaya and I) do not have write permission there. @dagendresen , do you by any chance?

No, I don't. [See permissions here](https://www-adm.nhm.uio.no/english/research/infrastructure/?vrtx=admin&mode=permissions).

I would suggest that adding webpages for the helpdesk under the MaNa group pages (or under the GBIF.no webpages) are more longterm than under the BioDT project pages. The BioDT project closes next year in May 2025.

**Comment by mariapie** [comment]
I have sent out an email to the communication group at UiO, I will let you know as soon as I hear from them

**Comment by mariapie** [comment]
Here the reply i have got: "Hei Elisa, dette egner seg nok ikke så godt for sosiale medier. Der når vi i tillegg til våre studenter og ansatte også ut til veldig mange andre. 
Hvilke andre kanaler har dere vurdert for å nå ut med dette? Har du snakket med Karenina?"  Have you already contacted Karenina Kriszat https://www.nhm.uio.no/english/about/organization/exhibitions-public-services/people/klkrisza/?

**Comment by rukayaj** [comment]
I have not contacted Karenina
