### ISSUE TITLE
TDWG Annual Conference 2023

### ISSUE THREAD

**Issue by ErikKusch** [uio-mana/CORE-Events#5]
# Quick Facts
## Abstract
TDWG 2023 will be a hybrid conference with in-person and virtual participants. All participants, including presenters, must register.

In-person registration includes: the welcome reception, coffee/tea breaks, lunch on session days, and the conference dinner. Excursions on Wednesday may entail an additional charge.

Both in-person and virtual participants will receive a login to the conference platform and will have access to live streamed presentations as well as session recordings as quickly as we can get them posted (we hope within 24 hours). Note that all sessions will be recorded. Virtual participants will be able to present any accepted contribution live, but it is vital to note that the time zone shift may mean that your presentation will be scheduled in the midde of your night. We will be unable to give all virtual presenters times that are convenient. Virtual presenters will be required to submit a pre-recorded video to serve as backup should a network problem arise.

Chat and message functions will support interaction among all participants.

## Logistics
- **External Link:** https://tdwg2023.zohobackstage.com.au/TDWG2023#/?lang=en
- **Dates**: 2023-10-09; 08:15 GMT+10 - 2023-10-13 15:00 GMT+10
- **Venue**: Hobart, Tasmania
- **Registration:** https://www.tdwg.org/conferences/2023/registration/
- **Host(s):** [CSIRO Hobart](https://www.csiro.au/en/about/locations/state-locations/tas/hobart)

## Related Project(s)
[BioDT](https://github.com/uio-mana/CORE-Projects/issues/3)
[GBIF.NO_21-25](https://github.com/uio-mana/CORE-Projects/issues/1)

# Post-Event Summary
## Outcome
Conference happened. Rukaya organised AI session. Dag, Carrie, and Erik attended in person.

**Comment by ErikKusch** [comment]
Just pinging @MichalTorma and @rukayaj here to discuss: 

1. who will be attending TDWG in person/remotely  
2. which flight connections to take
3. which hotel to stay in

and, on a personal note:

4. if anyone wants to join [this hike](https://www.trailhiking.com.au/hikes/western-arthurs-a-k/) with me after TDWG

**Comment by rukayaj** [comment]
I don't think I'm attending this one in person, but I will definitely attend remotely :) that hike looks freaking awesome though!!!

**Comment by rukayaj** [comment]
It sounds like Knut and Hugo are going though, maybe they want to join? You might do better trying to organise over email

**Comment by dagendresen** [comment]
Some are choosing the Mövenpick Hotel Hobart: Veronika (SWE), Dag, ...

**Comment by ErikKusch** [comment]
Conference was attended by @rukayaj , @cjandrew , @dagendresen , and @ErikKusch.
