### ISSUE TITLE
GBIF GB30 Governing Board 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/CORE-Events#6]
# Quick Facts
## Abstract
The GB30 meeting and associated events will take place in Canberra, Austalia in the period 15-20 October 2023.

Prior to the GB30 events, the [TDWG 2023 Conference](https://www.tdwg.org/conferences/2023/) takes place on 9-13 October in Hobart, Tasmania and some GB30 attendees may also be attending this conference.

## Logistics
- **External Link:** https://gb30.gbif.org/
- **Dates**: 2023-10-15; 00:00 GMT+10 - 2023-10-20; 24:00 GMT+10
- **Venue**: Canberra, Australia
- **Host(s):** [GBIF Australia](https://www.gbif.org/country/AU/summary)

## Related Project(s)
[GBIF.NO_21-25](https://github.com/uio-mana/CORE-Projects/issues/1)

# Post-Event Summary
## Outcome
Event happened.

**Comment by dagendresen** [comment]
Dag: Sat 14/10: HBA 12:40 --> CBR 15:55; QT Canberra Hotel; Sun 22/10: SYD 19:05 --> Mon 23/10: SIN 00:20; SIN 01:10 --> LHR 07:45; LHR 10:20 --> OSL 13:30

**Comment by ErikKusch** [comment]
Event has happened and was attended by @dagendresen.
