### ISSUE TITLE
BioDATA DNA South Africa 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/CORE-Events#8]
# Quick Facts
## Abstract
BioDATA Advanced is an international project between Norway and South Africa that aims to support students in upper education in developing skills in biodiversity data management and publishing, in addition to the most modern molecular methods for monitoring biodiversity. The skills taught within BioDATA Advanced are important for carrying out the everyday tasks of a modern biologist, though many of these skills are not taught in higher education. 

This project also looks to strengthen the partnership between the South African Node of the Global Biodiversity Information Facility (SANBI-GBIF) and the other BioDATA partners, through exchanges and enhanced collaborations on scientific projects of mutual interest.

This course will teach you how to access and use biodiversity data in your research.

## Logistics
- **External Link:** https://www.nhm.uio.no/english/research/projects/biodata-advanced/activities/2024-date-usage.html
- **Dates**: 2023-11-13; 00:00 CET - 2023-11-17; 24:00 CET
- **Venue**: Kruger National Park, South Africa
- **Host(s)**: [MANA](https://www.nhm.uio.no/english/research/groups/mana/index.html)

## Related Project(s)
[BioDATA2.0](https://github.com/uio-mana/CORE-Projects/issues/4)

# Post-Event Summary
## Outcome
Event happened.

**Comment by ErikKusch** [comment]
Event has happened.
